name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build ./Src/All.sln
    - name: Mailer Tests
      run: dotnet test --no-build ./Src/UnitTests/MailerUnitTests/MailerUnitTests.csproj
    - name: Unit Tests
      run: dotnet test --no-build ./Src/UnitTests/CoravelUnitTests/CoravelUnitTests.csproj
    - name: Integration Tests
      run: dotnet test --no-build ./Src/IntegrationTests/Tests/Tests.csproj
